name: cherry
description: A Dart CLI to generate beautiful templates for MVC, MVVM, MVU patterns.
version: 0.0.1
homepage: null

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  ansicolor: ^2.0.0-nullsafety.0
  args: ^2.0.0
  dart_console: ^1.0.0
  http: ^0.13.0
  path: ^1.8.0
  tuple: ^2.0.0-nullsafety.0
  yaml: ^3.1.0

dev_dependencies:
  test: ^1.16.5

executables:
  cherry: main
