name: cherry
description: Dart CLI template generator and package manager for flutter, generate MVC, MVVM and MVU patterns.
version: 0.0.1-alpha
homepage: https://github.com/Sameerkash/cherry

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  ansicolor: ^2.0.0-nullsafety.0
  args: ^2.0.0
  dart_console: ^1.0.0
  http: ^0.13.1
  path: ^1.8.0
  tuple: ^2.0.0-nullsafety.0
  yaml: ^3.1.0

dev_dependencies:
  test: ^1.16.8

executables:
  cherry: cherry
